#!/bin/bash
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Uključite fotoaparat i fotografirati, fotografije ili slike s web-kamere. Više koristan nego igračku.\"},\"appDesc\": {\"message\": \"Uključite fotoaparat i fotografirati, fotografije ili slike s web-kamere. Više koristan nego igračku.\",\"description\":\"Uključite fotoaparat i fotografirati, fotografije ili slike s web-kamere. Više koristan nego igračku.\"}}" > hr/messages.json
echo "{\"appName\": {\"message\": \"Máy ảnh\",\"description\": \"Bật máy ảnh và chụp ảnh, hình ảnh, hoặc hình ảnh với webcam của bạn. Hữu ích hơn một món đồ chơi.\"},\"appDesc\": {\"message\": \"Bật máy ảnh và chụp ảnh, hình ảnh, hoặc hình ảnh với webcam của bạn. Hữu ích hơn một món đồ chơi.\",\"description\":\"Bật máy ảnh và chụp ảnh, hình ảnh, hoặc hình ảnh với webcam của bạn. Hữu ích hơn một món đồ chơi.\"}}" > vi/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Kamerayı açın ve resimler, fotoğraflar, ya da web kamerası ile resim çekmek. Bir oyuncak daha yararlı.\"},\"appDesc\": {\"message\": \"Kamerayı açın ve resimler, fotoğraflar, ya da web kamerası ile resim çekmek. Bir oyuncak daha yararlı.\",\"description\":\"Kamerayı açın ve resimler, fotoğraflar, ya da web kamerası ile resim çekmek. Bir oyuncak daha yararlı.\"}}" > tr/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Slå på kameran och ta bilder, bilder, eller en bild med din webbkamera. Mer användbar än en leksak.\"},\"appDesc\": {\"message\": \"Slå på kameran och ta bilder, bilder, eller en bild med din webbkamera. Mer användbar än en leksak.\",\"description\":\"Slå på kameran och ta bilder, bilder, eller en bild med din webbkamera. Mer användbar än en leksak.\"}}" > sv/messages.json
echo "{\"appName\": {\"message\": \"Camera\",\"description\": \"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\"},\"appDesc\": {\"message\": \"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\",\"description\":\"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\"}}" > en/messages.json
echo "{\"appName\": {\"message\": \"Camera\",\"description\": \"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\"},\"appDesc\": {\"message\": \"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\",\"description\":\"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\"}}" > en_GB/messages.json
echo "{\"appName\": {\"message\": \"Camera\",\"description\": \"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\"},\"appDesc\": {\"message\": \"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\",\"description\":\"Turn on camera and take pictures, photos, or a picture with your webcam. More useful than a toy.\"}}" > en_US/messages.json
echo "{\"appName\": {\"message\": \"Caméra\",\"description\": \"Allumez la caméra et prendre des photos, des photos ou une photo avec votre webcam. Plus utile qu'un jouet.\"},\"appDesc\": {\"message\": \"Allumez la caméra et prendre des photos, des photos ou une photo avec votre webcam. Plus utile qu'un jouet.\",\"description\":\"Allumez la caméra et prendre des photos, des photos ou une photo avec votre webcam. Plus utile qu'un jouet.\"}}" > fr/messages.json
echo "{\"appName\": {\"message\": \"Camera\",\"description\": \"Hidupkan kamera dan mengambil gambar, foto, atau gambar dengan kamera web anda. Lebih berguna daripada mainan.\"},\"appDesc\": {\"message\": \"Hidupkan kamera dan mengambil gambar, foto, atau gambar dengan kamera web anda. Lebih berguna daripada mainan.\",\"description\":\"Hidupkan kamera dan mengambil gambar, foto, atau gambar dengan kamera web anda. Lebih berguna daripada mainan.\"}}" > ms/messages.json
echo "{\"appName\": {\"message\": \"Câmera\",\"description\": \"Ligue a câmera e tirar fotos, fotos ou uma foto com sua webcam. Mais útil que um brinquedo.\"},\"appDesc\": {\"message\": \"Ligue a câmera e tirar fotos, fotos ou uma foto com sua webcam. Mais útil que um brinquedo.\",\"description\":\"Ligue a câmera e tirar fotos, fotos ou uma foto com sua webcam. Mais útil que um brinquedo.\"}}" > pt_BR/messages.json
echo "{\"appName\": {\"message\": \"Câmera\",\"description\": \"Ligue a câmera e tirar fotos, fotos ou uma foto com sua webcam. Mais útil que um brinquedo.\"},\"appDesc\": {\"message\": \"Ligue a câmera e tirar fotos, fotos ou uma foto com sua webcam. Mais útil que um brinquedo.\",\"description\":\"Ligue a câmera e tirar fotos, fotos ou uma foto com sua webcam. Mais útil que um brinquedo.\"}}" > pt_PT/messages.json
echo "{\"appName\": {\"message\": \"Aparat foto\",\"description\": \"Porniți aparatul foto și a face fotografii, fotografii sau o fotografie cu webcam-ul. Mai util decât o jucărie.\"},\"appDesc\": {\"message\": \"Porniți aparatul foto și a face fotografii, fotografii sau o fotografie cu webcam-ul. Mai util decât o jucărie.\",\"description\":\"Porniți aparatul foto și a face fotografii, fotografii sau o fotografie cu webcam-ul. Mai util decât o jucărie.\"}}" > ro/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Włącz aparat i robić zdjęcia, zdjęcia lub grafiki z kamery internetowej. Bardziej przydatne niż zabawki.\"},\"appDesc\": {\"message\": \"Włącz aparat i robić zdjęcia, zdjęcia lub grafiki z kamery internetowej. Bardziej przydatne niż zabawki.\",\"description\":\"Włącz aparat i robić zdjęcia, zdjęcia lub grafiki z kamery internetowej. Bardziej przydatne niż zabawki.\"}}" > pl/messages.json
echo "{\"appName\": {\"message\": \"Camera\",\"description\": \"I-on ang camera at kumuha ng litrato, mga larawan, o isang larawan gamit ang iyong webcam. Higit pang mga kapaki-pakinabang kaysa sa isang laruan.\"},\"appDesc\": {\"message\": \"I-on ang camera at kumuha ng litrato, mga larawan, o isang larawan gamit ang iyong webcam. Higit pang mga kapaki-pakinabang kaysa sa isang laruan.\",\"description\":\"I-on ang camera at kumuha ng litrato, mga larawan, o isang larawan gamit ang iyong webcam. Higit pang mga kapaki-pakinabang kaysa sa isang laruan.\"}}" > fil/messages.json
echo "{\"appName\": {\"message\": \"Cámara\",\"description\": \"Encienda la cámara y tomar fotos, fotografías, o una fotografía con tu cámara web. Más útil que un juguete.\"},\"appDesc\": {\"message\": \"Encienda la cámara y tomar fotos, fotografías, o una fotografía con tu cámara web. Más útil que un juguete.\",\"description\":\"Encienda la cámara y tomar fotos, fotografías, o una fotografía con tu cámara web. Más útil que un juguete.\"}}" > es/messages.json
echo "{\"appName\": {\"message\": \"Cámara\",\"description\": \"Encienda la cámara y tomar fotos, fotografías, o una fotografía con tu cámara web. Más útil que un juguete.\"},\"appDesc\": {\"message\": \"Encienda la cámara y tomar fotos, fotografías, o una fotografía con tu cámara web. Más útil que un juguete.\",\"description\":\"Encienda la cámara y tomar fotos, fotografías, o una fotografía con tu cámara web. Más útil que un juguete.\"}}" > es_419/messages.json
echo "{\"appName\": {\"message\": \"Càmera\",\"description\": \"Enceneu la càmera i fer fotos, fotografies, o una fotografia amb la teva càmera web. Més útil que una joguina.\"},\"appDesc\": {\"message\": \"Enceneu la càmera i fer fotos, fotografies, o una fotografia amb la teva càmera web. Més útil que una joguina.\",\"description\":\"Enceneu la càmera i fer fotos, fotografies, o una fotografia amb la teva càmera web. Més útil que una joguina.\"}}" > ca/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Tænd kamera og tage billeder, fotos, eller et billede med dit webcam. Mere nyttigt end et stykke legetøj.\"},\"appDesc\": {\"message\": \"Tænd kamera og tage billeder, fotos, eller et billede med dit webcam. Mere nyttigt end et stykke legetøj.\",\"description\":\"Tænd kamera og tage billeder, fotos, eller et billede med dit webcam. Mere nyttigt end et stykke legetøj.\"}}" > da/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Slå på kameraet og ta bilder, fotografier, eller et bilde med webkameraet. Mer nyttig enn et leketøy.\"},\"appDesc\": {\"message\": \"Slå på kameraet og ta bilder, fotografier, eller et bilde med webkameraet. Mer nyttig enn et leketøy.\",\"description\":\"Slå på kameraet og ta bilder, fotografier, eller et bilde med webkameraet. Mer nyttig enn et leketøy.\"}}" > no/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Hidupkan kamera dan mengambil gambar, foto, atau gambar dengan webcam Anda. Lebih berguna daripada mainan.\"},\"appDesc\": {\"message\": \"Hidupkan kamera dan mengambil gambar, foto, atau gambar dengan webcam Anda. Lebih berguna daripada mainan.\",\"description\":\"Hidupkan kamera dan mengambil gambar, foto, atau gambar dengan webcam Anda. Lebih berguna daripada mainan.\"}}" > id/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Ieslēdziet kameru un uzņemt attēlus, fotogrāfijas, vai arī ar savu webcam ainu. Vairāk noderīga, nekā rotaļlietu.\"},\"appDesc\": {\"message\": \"Ieslēdziet kameru un uzņemt attēlus, fotogrāfijas, vai arī ar savu webcam ainu. Vairāk noderīga, nekā rotaļlietu.\",\"description\":\"Ieslēdziet kameru un uzņemt attēlus, fotogrāfijas, vai arī ar savu webcam ainu. Vairāk noderīga, nekā rotaļlietu.\"}}" > lv/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Vklopite fotoaparat in slikal, fotografije ali slike s spletno kamero. Bolj koristno kot igrača.\"},\"appDesc\": {\"message\": \"Vklopite fotoaparat in slikal, fotografije ali slike s spletno kamero. Bolj koristno kot igrača.\",\"description\":\"Vklopite fotoaparat in slikal, fotografije ali slike s spletno kamero. Bolj koristno kot igrača.\"}}" > sl/messages.json
echo "{\"appName\": {\"message\": \"Fotoaparát\",\"description\": \"Zapnite fotoaparát a robiť fotografie, fotografia alebo obrázok s vašej webovej kamery. Užitočnejšie ako hračka.\"},\"appDesc\": {\"message\": \"Zapnite fotoaparát a robiť fotografie, fotografia alebo obrázok s vašej webovej kamery. Užitočnejšie ako hračka.\",\"description\":\"Zapnite fotoaparát a robiť fotografie, fotografia alebo obrázok s vašej webovej kamery. Užitočnejšie ako hračka.\"}}" > sk/messages.json
echo "{\"appName\": {\"message\": \"Fotoaparát\",\"description\": \"Zapněte fotoaparát a pořizovat fotografie, fotografie nebo obrázek s vaší webové kamery. Užitečnější než hračka.\"},\"appDesc\": {\"message\": \"Zapněte fotoaparát a pořizovat fotografie, fotografie nebo obrázek s vaší webové kamery. Užitečnější než hračka.\",\"description\":\"Zapněte fotoaparát a pořizovat fotografie, fotografie nebo obrázek s vaší webové kamery. Užitečnější než hračka.\"}}" > cs/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Schalten Sie die Kamera und machen Sie Fotos, Bilder, oder ein Bild mit Ihrer Webcam. Mehr nützlicher als ein Spielzeug.\"},\"appDesc\": {\"message\": \"Schalten Sie die Kamera und machen Sie Fotos, Bilder, oder ein Bild mit Ihrer Webcam. Mehr nützlicher als ein Spielzeug.\",\"description\":\"Schalten Sie die Kamera und machen Sie Fotos, Bilder, oder ein Bild mit Ihrer Webcam. Mehr nützlicher als ein Spielzeug.\"}}" > de/messages.json
echo "{\"appName\": {\"message\": \"Kaamera\",\"description\": \"Lülitage kaamera ja pildistada, fotosid või pilt oma veebikaamera. Kasulikum kui mänguasi.\"},\"appDesc\": {\"message\": \"Lülitage kaamera ja pildistada, fotosid või pilt oma veebikaamera. Kasulikum kui mänguasi.\",\"description\":\"Lülitage kaamera ja pildistada, fotosid või pilt oma veebikaamera. Kasulikum kui mänguasi.\"}}" > et/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Kytke kamera ja ottaa kuvia, valokuvia tai kuvan kanssa webcam. Enemmän hyötyä kuin lelu.\"},\"appDesc\": {\"message\": \"Kytke kamera ja ottaa kuvia, valokuvia tai kuvan kanssa webcam. Enemmän hyötyä kuin lelu.\",\"description\":\"Kytke kamera ja ottaa kuvia, valokuvia tai kuvan kanssa webcam. Enemmän hyötyä kuin lelu.\"}}" > fi/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Kurejea kwenye kamera na kuchukua picha, picha au picha ya pamoja na webcam yako. Muhimu zaidi kuliko toy.\"},\"appDesc\": {\"message\": \"Kurejea kwenye kamera na kuchukua picha, picha au picha ya pamoja na webcam yako. Muhimu zaidi kuliko toy.\",\"description\":\"Kurejea kwenye kamera na kuchukua picha, picha au picha ya pamoja na webcam yako. Muhimu zaidi kuliko toy.\"}}" > sw/messages.json
echo "{\"appName\": {\"message\": \"Fotocamera\",\"description\": \"Accendere la fotocamera e scattare foto, foto o una foto con la tua webcam. Più utile di un giocattolo.\"},\"appDesc\": {\"message\": \"Accendere la fotocamera e scattare foto, foto o una foto con la tua webcam. Più utile di un giocattolo.\",\"description\":\"Accendere la fotocamera e scattare foto, foto o una foto con la tua webcam. Più utile di un giocattolo.\"}}" > it/messages.json
echo "{\"appName\": {\"message\": \"Camera\",\"description\": \"Schakel de camera en foto's, foto's, of een foto met je webcam nemen. Nuttiger dan een stuk speelgoed.\"},\"appDesc\": {\"message\": \"Schakel de camera en foto's, foto's, of een foto met je webcam nemen. Nuttiger dan een stuk speelgoed.\",\"description\":\"Schakel de camera en foto's, foto's, of een foto met je webcam nemen. Nuttiger dan een stuk speelgoed.\"}}" > nl/messages.json
echo "{\"appName\": {\"message\": \"Fotoaparatas\",\"description\": \"Įjunkite fotoaparatą ir fotografuoti, nuotraukas, ar su savo kameros vaizdą. Daugiau naudingos ne žaislas.\"},\"appDesc\": {\"message\": \"Įjunkite fotoaparatą ir fotografuoti, nuotraukas, ar su savo kameros vaizdą. Daugiau naudingos ne žaislas.\",\"description\":\"Įjunkite fotoaparatą ir fotografuoti, nuotraukas, ar su savo kameros vaizdą. Daugiau naudingos ne žaislas.\"}}" > lt/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Kapcsolja be a kamerát, és képeket, fényképeket, vagy egy képet a webkamera. Hasznosabb, mint egy játék.\"},\"appDesc\": {\"message\": \"Kapcsolja be a kamerát, és képeket, fényképeket, vagy egy képet a webkamera. Hasznosabb, mint egy játék.\",\"description\":\"Kapcsolja be a kamerát, és képeket, fényképeket, vagy egy képet a webkamera. Hasznosabb, mint egy játék.\"}}" > hu/messages.json
echo "{\"appName\": {\"message\": \"Κάμερα\",\"description\": \"Ενεργοποιήστε τη φωτογραφική μηχανή και να τραβάτε φωτογραφίες, εικόνες, ή μια φωτογραφία με την κάμερα σας. Πιο χρήσιμο από ένα παιχνίδι.\"},\"appDesc\": {\"message\": \"Ενεργοποιήστε τη φωτογραφική μηχανή και να τραβάτε φωτογραφίες, εικόνες, ή μια φωτογραφ^uία με την κάμερα σας. Πιο χρήσιμο από ένα παιχνίδι.\",\"description\":\"Ενεργοποιήστε τη φωτογραφική μηχανή και να τραβάτε φωτογραφίες, εικόνες, ή μια φωτογραφία με την κάμερα σας. Πιο χρήσιμο από ένα παιχνίδι.\"}}" > el/messages.json
echo "{\"appName\": {\"message\": \"Камера\",\"description\": \"Укључите фотоапарат и сликају, фотографије или слике са веб камере. Више него корисно играчка.\"},\"appDesc\": {\"message\": \"Укључите фотоапарат и сликају, фотографије или слике са веб камере. Више него корисно играчка.\",\"description\":\"Укључите фотоапарат и сликају, фотографије или слике са веб камере. Више него корисно играчка.\"}}" > sr/messages.json
echo "{\"appName\": {\"message\": \"Камера\",\"description\": \"Увімкніть камеру і знімати фотографії, фотографії, або картинку з веб-камери. Корисніші, ніж іграшка.\"},\"appDesc\": {\"message\": \"Увімкніть камеру і знімати фотографії, фотографії, або картинку з веб-камери. Корисніші, ніж іграшка.\",\"description\":\"Увімкніть камеру і знімати фотографії, фотографії, або картинку з веб-камери. Корисніші, ніж іграшка.\"}}" > uk/messages.json
echo "{\"appName\": {\"message\": \"Камера\",\"description\": \"Включете фотоапарата и да правите снимки, снимки, или снимка с вашата уеб камера. По-полезно от играчка.\"},\"appDesc\": {\"message\": \"Включете фотоапарата и да правите снимки, снимки, или снимка с вашата уеб камера. По-полезно от играчка.\",\"description\":\"Включете фотоапарата и да правите снимки, снимки, или снимка с вашата уеб камера. По-полезно от играчка.\"}}" > bg/messages.json
echo "{\"appName\": {\"message\": \"Камера\",\"description\": \"Включите камеру и снимать фотографии, фотографии, или картинку с веб-камеры. Более полезны, чем игрушка.\"},\"appDesc\": {\"message\": \"Включите камеру и снимать фотографии, фотографии, или картинку с веб-камеры. Более полезны, чем игрушка.\",\"description\":\"Включите камеру и снимать фотографии, фотографии, или картинку с веб-камеры. Более полезны, чем игрушка.\"}}" > ru/messages.json
echo "{\"appName\": {\"message\": \"מצלמה\",\"description\": \"הפעל את המצלמה ולצלם תמונות, תמונות, או תמונה עם מצלמת האינטרנט שלך. שימושי יותר מצעצוע.\"},\"appDesc\": {\"message\": \"הפעל את המצלמה ולצלם תמונות, תמונות, או תמונה עם מצלמת האינטרנט שלך. שימושי יותר מצעצוע.\",\"description\":\"הפעל את המצלמה ולצלם תמונות, תמונות, או תמונה עם מצלמת האינטרנט שלך. שימושי יותר מצעצוע.\"}}" > he/messages.json
echo "{\"appName\": {\"message\": \"دوربین\",\"description\": \"به نوبه خود بر روی دوربین و گرفتن عکس، عکس، و یا یک عکس با وب کم خود. مفید تر از یک اسباب بازی.\"},\"appDesc\": {\"message\": \"به نوبه خود بر روی دوربین و گرفتن عکس، عکس، و یا یک عکس با وب کم خود. مفید تر از یک اسباب بازی.\",\"description\":\"به نوبه خود بر روی دوربین و گرفتن عکس، عکس، و یا یک عکس با وب کم خود. مفید تر از یک اسباب بازی.\"}}" > fa/messages.json
echo "{\"appName\": {\"message\": \"كاميرا\",\"description\": \"تشغيل الكاميرا والتقاط الصور، والصور، أو صورة مع كاميرا ويب الخاص بك. أكثر فائدة من لعبة.\"},\"appDesc\": {\"message\": \"تشغيل الكاميرا والتقاط الصور، والصور، أو صورة مع كاميرا ويب الخاص بك. أكثر فائدة من لعبة.\",\"description\":\"تشغيل الكاميرا والتقاط الصور، والصور، أو صورة مع كاميرا ويب الخاص بك. أكثر فائدة من لعبة.\"}}" > ar/messages.json
echo "{\"appName\": {\"message\": \"कैमरा\",\"description\": \"कैमरे पर मुड़ें और चित्र, तस्वीरें, या अपने वेब कैमरा के साथ एक तस्वीर ले लो. एक खिलौने की तुलना में अधिक उपयोगी है.\"},\"appDesc\": {\"message\": \"कैमरे पर मुड़ें और चित्र, तस्वीरें, या अपने वेब कैमरा के साथ एक तस्वीर ले लो. एक खिलौने की तुलना में अधिक उपयोगी है.\",\"description\":\"कैमरे पर मुड़ें और चित्र, तस्वीरें, या अपने वेब कैमरा के साथ एक तस्वीर ले लो. एक खिलौने की तुलना में अधिक उपयोगी है.\"}}" > hi/messages.json
echo "{\"appName\": {\"message\": \"กล้อง\",\"description\": \"เปิดสวิตช์กล้องถ่ายภาพและภาพถ่ายหรือภาพที่มีเว็บแคมของคุณ มีประโยชน์มากกว่าของเล่น\"},\"appDesc\": {\"message\": \"เปิดสวิตช์กล้องถ่ายภาพและภาพถ่ายหรือภาพที่มีเว็บแคมของคุณ มีประโยชน์มากกว่าของเล่น\",\"description\":\"เปิดสวิตช์กล้องถ่ายภาพและภาพถ่ายหรือภาพที่มีเว็บแคมของคุณ มีประโยชน์มากกว่าของเล่น\"}}" > th/messages.json
echo "{\"appName\": {\"message\": \"카메라\",\"description\": \"카메라의 전원을 켜고 사진, 사진, 또는 당신의 웹캠 사진 촬영을합니다. 장난감보다 더 유용합니다.\"},\"appDesc\": {\"message\": \"카메라의 전원을 켜고 사진, 사진, 또는 당신의 웹캠 사진 촬영을합니다. 장난감보다 더 유용합니다.\",\"description\":\"카메라의 전원을 켜고 사진, 사진, 또는 당신의 웹캠 사진 촬영을합니다. 장난감보다 더 유용합니다.\"}}" > ko/messages.json
echo "{\"appName\": {\"message\": \"カメラ\",\"description\": \"カメラの電源を入れ、映像、写真、またはあなたのウェブカメラで写真を撮る。おもちゃよりも便利。\"},\"appDesc\": {\"message\": \"カメラの電源を入れ、映像、写真、またはあなたのウェブカメラで写真を撮る。おもちゃよりも便利。\",\"description\":\"カメラの電源を入れ、映像、写真、またはあなたのウェブカメラで写真を撮る。おもちゃよりも便利。\"}}" > ja/messages.json
echo "{\"appName\": {\"message\": \"相机\",\"description\": \"开启相机并拍照，照片或图片与您的网络摄像头。比玩具更多有用。\"},\"appDesc\": {\"message\": \"开启相机并拍照，照片或图片与您的网络摄像头。比玩具更多有用。\",\"description\":\"开启相机并拍照，照片或图片与您的网络摄像头。比玩具更多有用。\"}}" > zh_CN/messages.json
echo "{\"appName\": {\"message\": \"相機\",\"description\": \"開啟相機並拍照，照片或圖片與您的網絡攝像頭。比玩具更多有用。\"},\"appDesc\": {\"message\": \"開啟相機並拍照，照片或圖片與您的網絡攝像頭。比玩具更多有用。\",\"description\":\"開啟相機並拍照，照片或圖片與您的網絡攝像頭。比玩具更多有用。\"}}" > zh_TW/messages.json
