var g=this;var h={},i=function(a,b){h[a]||(h[a]=[]);h[a].push(b)};chrome.extension.onMessage.addListener(function(a,b,e){var c=a.type,d=a.data;if(h[c]){var f=function(a,b){e({type:a,data:b})};h[c].forEach(function(a){a(d,b,f)})}});var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-31000769-1"]);var j=_gaq,k=["_gaq"],l=g;!(k[0]in l)&&l.execScript&&l.execScript("var "+k[0]);for(var m;k.length&&(m=k.shift());){var n;if(n=!k.length)n=void 0!==j;n?l[m]=j:l=l[m]?l[m]:l[m]={}}
var p=function(a){this.a=a},r=function(a,b,e,c){for(var d=1;5>=d;++d)_gaq.push(["_deleteCustomVar",d]);if(c&&c.length){var f=Math.pow(2,5)-1;c.forEach(function(a){var b=a[0]-1;f&&f&1<<b&&(_gaq.push(["_setCustomVar"].concat(a)),f^=1<<b)})}_gaq.push(["_trackEvent",a.a,b,e])},s=new p("Theme"),t=new p("PlusOne");chrome.i18n.getMessage("untitled");chrome.i18n.getMessage("@@bidi_dir");chrome.i18n.getMessage("locale");var u=null,v=null,x=function(){v.objectStoreNames.contains("MCT Store")||w()},w=function(){v.createObjectStore("MCT Store",{keyPath:"timestamp",autoIncrement:!0})};var y={};this.instantiated=!1;function z(a,b,e){var c;a:{a=a.data.guid;try{for(var d=JSON.parse(localStorage.getItem("themes")),f=d.length-1;0<=f;f--){var q=JSON.parse(localStorage.getItem(d[f]));if(!/^https?:\/\//.test(q.urls.crx)){c=null;break a}if(a==q.guid){c=q;break a}}}catch(I){c=null;break a}c=void 0}d={canDelete:!1};c&&(d.canDelete=!0,d.themeInfo={id:c.id,secret:c.secret,guid:c.guid});e("candelete",d)}
function A(a){if("deleted"==a.status&&(a=a.data.themeId,localStorage.getItem(a))){var b=JSON.parse(localStorage.getItem("themes")),e=b.indexOf(a);-1!=e&&(b.splice(e,1),localStorage.setItem("themes",JSON.stringify(b)));localStorage.removeItem(a);chrome.extension.sendMessage({type:"analytics",data:{status:"delete",data:{type:"Theme"}}},function(){})}}
function B(a){if(window.navigator.onLine)a&&C(a);else if(a){var b={};b.timestamp=(new Date).getTime();b.track=a;try{var e=v.transaction(["MCT Store"],"readwrite").objectStore("MCT Store").put(b);e.onsuccess=function(){};e.onerror=function(){}}catch(c){}}}function C(a){"Theme"==a.data.type?r(s,a.status,a.data.label,a.data.opt_vars):"PlusOne"==a.data.type&&r(t,a.status,a.data.label,a.data.opt_vars)}function D(){y.onOnline=setTimeout(E,7E3)}function F(){G()}
function G(){if(y&&void 0===!y.length)for(var a in y)y.hasOwnProperty(a)&&clearTimeout(y[a]);y={}}
function E(){try{if(G(),window.navigator.onLine){var a=function(a){a&&a.length&&function H(b){if(window.navigator.onLine){var c=a[b].track;if(c){C(c);c=a[b].timestamp;try{var d=v.transaction(["MCT Store"],"readwrite").objectStore("MCT Store")["delete"](c);d.onsuccess=function(){};d.onerror=function(){}}catch(e){}}b++;b<a.length&&(G(),y.iterateEvents=setTimeout(function(){H(b)},5E3))}}(0)};try{var b=v.transaction(["MCT Store"],"readonly").objectStore("MCT Store");if(b.getAll)b.getAll().onsuccess=function(b){a&&
a(b.target.result)};else try{var e=[];v.transaction(["MCT Store"],"readonly").objectStore("MCT Store").openCursor().onsuccess=function(b){(b=b.target.result)?(e.push(b.value),b["continue"]()):a&&a(e)}}catch(c){}}catch(d){}}}catch(f){G()}}
g.window.addEventListener("load",function(){var a=chrome.extension.getBackgroundPage();if(!a.instantiated){a.instantiated=!0;try{u=window.indexedDB||window.webkitIndexedDB||window.mozIndexedDB||window.msIndexedDB;var b=u.open("MCT Analytics",1,"Analytics event storage for offline events");b.onsuccess=function(a){v||(v=a.target.result);1!=v.version&&(v.setVersion(1).onsuccess=x)};b.onupgradeneeded=function(a){v||(v=a.target.result);w()};b.onerror=function(){}}catch(e){}a=document.createElement("script");
a.async=!0;a.src="https://ssl.google-analytics.com/ga.js";b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b);i("delete",A);i("candelete",z);i("analytics",B);g.window.addEventListener("online",D,!1);g.window.addEventListener("offline",F,!1);try{var c=JSON.parse(localStorage.getItem("guids")),d=localStorage.getItem("themes"),d=d?JSON.parse(d):[];c.forEach(function(a){try{var b=JSON.parse(localStorage.getItem(a)),c={desc:""};c.guid=b.guid;c.name=b.name;c.secret=b.secret;c.isShared=
!0;c.urls={crx:"https://www.mychrometheme.com/install/"+a+"/"+b.secret,zip:"",preview_large:"https://www.mychrometheme.com/preview/"+a+"/"+b.secret,preview_small:b.thumb,share:b.url};c.secret=b.secret;c.id="theme-"+a;localStorage.setItem(c.id,JSON.stringify(c));d.push(c.id);localStorage.removeItem(a)}catch(e){}});localStorage.setItem("themes",JSON.stringify(d));localStorage.removeItem("guids")}catch(f){}window.navigator.onLine&&(y.onload=setTimeout(E,1E4))}},!1);
